source: .

paths:
  uploads: public/assets/uploads
  static: public

collections_config:
  pages:
    path: src/content/pages
    name: Pages
    icon: web
    schemas:
      home:
        path: .cloudcannon/schemas/home.mdx
        name: Home Page

  publications:
    path: src/content/publications
    name: Publications
    icon: article
    schemas:
      default:
        path: .cloudcannon/schemas/publication.mdx
        name: Publication

  research:
    path: src/content/research
    name: Research
    icon: science
    schemas:
      default:
        path: .cloudcannon/schemas/research.mdx
        name: Research Project

  news:
    path: src/content/news
    name: News
    icon: campaign
    schemas:
      default:
        path: .cloudcannon/schemas/news.mdx
        name: News Item

  academic_info:
    path: src/content/academic-info
    name: Academic Info
    icon: school
    schemas:
      default:
        path: .cloudcannon/schemas/academic-info.mdx
        name: Academic Info Item

  settings:
    path: src/data
    name: Site Settings
    icon: settings
    disable_add: true

collection_groups:
  - heading: Pages
    collections:
      - pages
      - settings
  - heading: Content
    collections:
      - publications
      - research
      - news
      - academic_info

data_config:
  site:
    path: src/data/site.json

preview:
  generate:
    command: CLOUDCANNON=1 npm run build
    output: dist

editor:
  default_path: /
